branches:
  only:
  - master

os: linux

dist: focal

language: minimal

git:
  quiet: true

cache:
  directories:
    - /home/travis/cache

env:
  global:
    - LANG=en_US.UTF-8
    - REPO_MAKE_CACHE=$HOME/cache
    - REPO_MAKE_PKGBUILDS=$TRAVIS_BUILD_DIR

stages:
  - download
  - build
  - upload

jobs:
  include:
    - stage: download
      name: Download current repo state
      script:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch gh-pages --single-branch $HOME/repo || true
        - rm -rf $HOME/repo/.git
      workspaces:
        create:
          name: repo
          paths:
            - $HOME/repo/

    - stage: build
      name: Build x86_64 packages
      env: REPO_MAKE_ARCH=x86_64 REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg.conf REPO_MAKE_TARGET=$HOME/repo/x86_64
      arch: amd64
      workspaces:
        use:
          - repo
        create:
          name: x86_64
          paths: $HOME/repo/x86_64
      script:
        - sudo locale-gen en_US.UTF-8
        - sudo update-locale LANG=en_US.UTF-8
        - sudo ./.ci/repo-make-ci.sh

    - stage: build
      name: Build armv6h packages
      env: REPO_MAKE_ARCH=armv6h REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg-armv6h.conf REPO_MAKE_TARGET=$HOME/repo/armv6h
      arch: arm64
      workspaces:
        use:
          - repo
        create:
          name: armv6h
          paths: $HOME/repo/armv6h
      script:
        - sudo locale-gen en_US.UTF-8
        - sudo update-locale LANG=en_US.UTF-8
        - sudo dpkg --add-architecture armhf
        - sudo apt-get update
        - sudo apt-get install crossbuild-essential-armhf
        - cat repo-make-arm.conf > repo-make.conf
        - sudo ./.ci/repo-make-ci.sh

    - stage: build
      name: Build armv7h packages
      env: REPO_MAKE_ARCH=armv7h REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg-armv7h.conf REPO_MAKE_TARGET=$HOME/repo/armv7h
      arch: arm64
      workspaces:
        use:
          - repo
        create:
          name: armv7h
          paths: $HOME/repo/armv7h
      script:
        - sudo locale-gen en_US.UTF-8
        - sudo update-locale LANG=en_US.UTF-8
        - sudo dpkg --add-architecture armhf
        - sudo apt-get update
        - sudo apt-get install crossbuild-essential-armhf
        - cat repo-make-arm.conf > repo-make.conf
        - sudo ./.ci/repo-make-ci.sh

    - stage: upload
      name: Upload repository
      workspaces:
        use:
          - x86_64
          - armv6h
          - armv7h
      before_deploy:
        - sudo chown -R $USER:$USER $HOME/repo
        - ./.ci/genindex.sh $HOME/repo $(basename $TRAVIS_REPO_SLUG)
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        skip_cleanup: true
        local_dir: $HOME/repo/
        strategy: git
        on:
          repo: $TRAVIS_REPO_SLUG
          branch: tmn505
